default_context:
  project_name: 'SolarHouse'
  project_slug: 'solarhouse'
  domain_main: 'sibecodome.org'
  domain_staging: 'stag.sibecodome.org'
  docker_swarm_stack_name_main: 'sibecodome-org'
  docker_swarm_stack_name_staging: 'stag-sibecodome-org'
  secret_key: 'SECRET_KEY'
  first_superuser: 'yaricp@gmail.com'
  first_superuser_password: 'ZhjckfdBR5'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.sibecodome.org", "https://stag.sibecodome.org", "https://sibecodome.org", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sibecodome.org'
  postgres_password: 'postgres_pass'
  pgadmin_default_user: 'yaricp@gmail.com'
  pgadmin_default_user_password: 'ZhjckfdBR5'
  traefik_constraint_tag: 'sibecodome.org'
  traefik_constraint_tag_staging: 'stag.sibecodome.org'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ZhjckfdBR5'
  sentry_dsn: ''
  docker_image_prefix: 'sh'
  docker_image_backend: 'shbackend'
  docker_image_celeryworker: 'shceleryworker'
  docker_image_frontend: 'shfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
